title: My Reading Blog
description: Book reviews and reading notes
baseurl: ""
url: "https://usanas7.github.io"

theme: minima

# Simple navigation
header_pages:
  - about.markdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag